### ISSUE TITLE
[SDL 0104] Security ATF feature

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_atf#105]
Proposal: [Security ATF feature](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0104-atf_security_proposal.md)

This proposal describes support of security sessions in ATF (Automated Test Framework).
ATF should be able to test SDL security feature.

Main ATF features for checking SDL security are:
 - Support of secure SDL sessions;
 - Support of testing broken handshake;
 - Support of sending raw data in secure channel;
 - Support of expected secure requests\responses\notifications;
 - Support Transport Layer Security (TLS) and Datagram Transport Layer Security (DTLS). 

Review: https://github.com/smartdevicelink/sdl_evolution/issues/310

**Comment by JackLivio** [comment]
Fixed by #107 and #136
