### ISSUE TITLE
ATF does not disable HB by using HB flags

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_atf#108]
**Occurrence: Always**

# Description
ATF doe not disable HB by using HB flags sendHeartbeatToSDL = false,   self.heartbeatEnabled = false in case of 2 connections.

## Steps to reproduce
1. Execute attached DisableHB.lua script

Steps in script:
1. ATF starts SDL and performs initialization of HMI.
2. Opens 2 connections and in fist connection HB is disabled.

## Expected result
Wait function is executed without any fails and interruptions.

## Actual result
ATF closes fist session by HB timeout.

# Environment
SDL commit: develop 4eb09bf
OS with SDL: Ubuntu 16.04
VM used for OS with SDL (yes/no): (**no** by default)
ATF version: a6a2a9b2cde
Transport: TCP

# Attachments
Note: extract attached files in 'atf/test_scripts/Defects' folder
[Defects.zip](https://github.com/smartdevicelink/sdl_atf/files/1534165/Defects.zip)

**Comment by dboltovskyi** [comment]
Issue is not actual for current develop
