### ISSUE TITLE
Which part of SDL is this testing framework for?

### ISSUE THREAD

**Issue by JackLivio** [smartdevicelink/sdl_atf#11]
Is this a testing framework for SDL Core?

**Comment by pestOO** [comment]
@JackLivio, yes It is for testing https://github.com/smartdevicelink/sdl_core functionality.

**Comment by JackLivio** [comment]
Are the gmock tests included in the sdl_core repository no longer supported? i.e. running 
```
make test
```

**Comment by pestOO** [comment]
@JackLivio,
Gmock is a framework for Component (unit) testing SDL.
ATF is a framework for System (functional) testing.
Both type of testing are applicable for SDL at this momemnt.

**Comment by JackLivio** [comment]
Thank you
