### ISSUE TITLE
[SDL 0206] - Remote Automated Testing

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_atf#159]
Proposal: [Remote Automated Testing](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0206-remote_atf_testing.md)

> This proposal is about modification of Automated Test Framework (ATF) for providing ability to test SDL on remote workstations using automated test scripts.

https://github.com/smartdevicelink/sdl_evolution/issues/633

Steering Committee Decision:

> The Steering Committee voted to fully accept this proposal on 2019-01-15.

**Comment by jacobkeeler** [comment]
Closing with the merge of #180
