### ISSUE TITLE
Disable unused SDL loggers

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_atf#175]
By default SDL has a few loggers enabled (see `log4cxx.properties` file). 
Three of them save data to files:
 - SmartDeviceLinkCoreLogFile => SmartDeviceLinkCore.log
 - TransportManagerLogFile => TransportManager.log
 - ProtocolFordHandlingLogFile => ProtocolFordHandling.log

Nevertheless ATF gets SDL logs trough `Telnet` logger which is not utilize files at all.
The idea is to disable some of the SDL loggers which writes data to file system.
This increase performance on environments with parallel test execution.

**Comment by iCollin** [comment]
Closed via #176
