### ISSUE TITLE
Sometimes ATF is unable to parse multi-frame messages for 2 mobile sessions

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_atf#177]
Sometimes ATF is unable to parse multi-frame messages for 2 mobile sessions.
This is happened when SDL sends large messages which needs to be split into pieces (multi-frames) on a one mobile connection and for 2 or more mobile sessions simultaneously. 

This leads to aborting of ATF script with error:
```
QIODevice::read (QTcpSocket): device not open
PANIC: unprotected error in call to Lua API (./modules/protocol_handler/protocol_handler.lua:291: attempt to perform arithmetic on field 'totalSize' (a nil value))

```

**Comment by jacobkeeler** [comment]
@dboltovskyi Could you provide a script which shows this bug?

**Comment by dboltovskyi** [comment]
@jacobkeeler Unfortunately I was not able to create specific script which reproduces this issue with 100% likelihood.
However we noticed that [079_ATF_PTU_HMI_Level_Affected_Apps_NONE_BACKGROUND_HTTP](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/build_options/079_ATF_PTU_HMI_Level_Affected_Apps_NONE_BACKGROUND_HTTP.lua) script fails sometimes due to this issue.
Since this script is in our regression set which runs on every fix and update in develop we could see this issue quite often.

**Comment by jacobkeeler** [comment]
Closing with the merge of #178

**Comment by LuxoftAKutsan** [comment]
@jacobkeeler should it be closed?

**Comment by dboltovskyi** [comment]
Closing with the merge of #178
