### ISSUE TITLE
[SDL 0328] Modernize Ubuntu Support V20 LTS

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_atf#219]
**Proposal:** [Modernize Ubuntu Support V20 LTS](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0328-modernize-ubuntu-support-v20.md)

> This proposal would like to provide support for Ubuntu 20 LTS and bump the minimum required version of Ubuntu to Ubuntu 18 LTS. Currently Ubuntu 18 is the recommended platform and Ubuntu 16 is the minimum required version.

>These changes will mainly affect the build process for SDL Core and ATF.

**Review:** https://github.com/smartdevicelink/sdl_evolution/issues/1103

**Steering Committee Decision:** 
The Steering Committee voted to fully accept this proposal.

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_atf/pull/231
