### ISSUE TITLE
ATF cannot find MOBILE_API.xml outside of `components/interfaces`

### ISSUE THREAD

**Issue by iCollin** [smartdevicelink/sdl_atf#242]
Since https://github.com/smartdevicelink/sdl_core/pull/3778 ATF is unable to find and parse the MOBILE_API.xml, causing parallel runs to fall back to the XML within the `data` folder and causing normal runs to fail outright.

Some changes are needed to find the MOBILE_API.xml within the rpc_spec submodule.

Perhaps also some changes could be added so that parallel runs print a warning when falling back to an older API XML.

**Comment by ShobhitAd** [comment]
Closed via https://github.com/smartdevicelink/sdl_atf/pull/243
